### ISSUE TITLE
cannot resolve symbol 'MainActivity'

### ISSUE THREAD

**Issue by Nazar-Pa** [abhi007tyagi/Android_Dialogflow_Chatbot_Library#1]
Hi bro. First thank you for your very helpful explanation. I am also making a chatbot and need some interactive buttons as well. I would like to know if you can help me in some cases that I do not understand and having issues when I am setting your chatbot example? 
I actually have set your previous example as you mentioned in blog and it works very well for me. Now I need this one to add some buttons and so on. 
1. When I add this snippet below, to the ChatbotActivity class I encountered an error "cannot resolve symbol 'MainActivity'", how can I solve this issue, sorry for this question because I have no previous experience with android development.

![image](https://user-images.githubusercontent.com/55276028/87458385-30dd3f00-c60a-11ea-9d78-af23e06a0a7f.png)

And this the error: 
![image](https://user-images.githubusercontent.com/55276028/87458317-173bf780-c60a-11ea-824d-402c8d71a6d4.png)

**Comment by abhi007tyagi** [comment]
@Nazar-Pa that is for reference bro. Use the class name in which you are calling the chatbot!
