### ISSUE TITLE
app crashes on heroku

### ISSUE THREAD

**Issue by Nazar-Pa** [abhi007tyagi/Android_Dialogflow_Chatbot_Library#2]
Hey bro, it is me again. 
I am trying to set your sample webhook node.js. Therefore I deployed it to Heroku, but the application crashes on heroku. I hope this is the right thing that I am deploying it to heroku to use it in webhook fulfillment through dialogflow. If this is not right way, what should I do with this sample nodejs code to set up this example? Thanks in advance.

**Comment by abhi007tyagi** [comment]
@Nazar-Pa Please do not raise issues if you do not know or understand certain things. It is assumed, that you should have a basic understanding of NodeJS services and how to run them locally. 
You should run your NodeJS server locally and expose the service to internet using NGROK or similar to Dialogflow as fulfillment.

If you know other ways of creating rest services, then use them. Just make sure, your response has params that match the required format.
