### ISSUE TITLE
app stops working when using button template

### ISSUE THREAD

**Issue by Nazar-Pa** [abhi007tyagi/Android_Dialogflow_Chatbot_Library#3]
Hey, sorry for disturbing again. The app stops working when I try show messages with Buttons. I attach the screenshot from Logcat, There occurs error, and I could not find the solution. Do you perhaps have any idea what can be the issue?
![image](https://user-images.githubusercontent.com/55276028/87739250-b403be00-c7df-11ea-8439-b00cefe500ab.png)

**Comment by abhi007tyagi** [comment]
@Nazar-Pa make sure you are sending the correct payload
`{"template": "button", "buttonItems":[{"uiText":"Action 1", "actionText":"action 1 selected", "isPositive": true},{"uiText":"Action 2", "actionText":"action 2 selected", "isPositive": false}], "align": "h", "size":"l", "eventToCall":"android_event" };`

Even spelling mistake can cause a null pointer exception at the moment.
In the above JSON, make sure all the keys are present with correct spelling and case.

**Comment by abhi007tyagi** [comment]
@Nazar-Pa see if you are sending **buttonItems** or not. If yes, check spelling.

**Comment by Nazar-Pa** [comment]
I got your SampleDialogflowWebhook and using exactly same code without changing anything. 
![image](https://user-images.githubusercontent.com/55276028/87740055-8c155a00-c7e1-11ea-92d8-725d3eff45bf.png)

I also created an "Capture Android Event" and added an "android_event" event to that intent. 
![image](https://user-images.githubusercontent.com/55276028/87740195-deef1180-c7e1-11ea-838c-a9eb85ea1179.png)

I can only get response when I switch it to "const params = { "template": "text" }", so with text there is no error.

**Comment by Nazar-Pa** [comment]
As I said it works flawlessly when I am showing a simple text.

![image](https://user-images.githubusercontent.com/55276028/87741817-b49f5300-c7e5-11ea-8947-d0999d3872e4.png)

However I also noticed that in your screenshot you get response as "This is a message section for showing text" with simple text template. I do not know if I am doing something wrong. Because I get response as "Event captured successfully!" (below)

![109755590_733425940809343_3624293363880601593_n](https://user-images.githubusercontent.com/55276028/87741901-df89a700-c7e5-11ea-92b9-ef5e923f1687.png)

**Comment by abhi007tyagi** [comment]
@Nazar-Pa do you see buttons on UI? How are you sending event if they are not?

**Comment by abhi007tyagi** [comment]
@Nazar-Pa please uncomment the line
 const param_context = {name: "param_context", lifespan: 10, parameters: params};
Without this, you cannot set parameters to context!

It should work.

**Comment by Nazar-Pa** [comment]
It never worked with Heroku. I ran it using Ngrok then it worked only once (with hyperlink) but failed again when I checked it few times more. I did not understand how this might happen if it worked once. Thank you very much anyway. I can send you my ngrok link if you still keep the app working somewhere, to check if it works with you. If not never mind, I will try to find the issue.

**Comment by abhi007tyagi** [comment]
@Nazar-Pa the screenshot you shared, I see you have one line of code commented. Uncomment it as I said earlier.

**Comment by Nazar-Pa** [comment]
Yes I did it. Still the same error and no answer. But as I said it worked
just one time

**Comment by abhi007tyagi** [comment]
@Nazar-Pa did you restarted your service after the code change? Or stop NGROK and try again?
If you still get error, share the NGROK URL

**Comment by abhi007tyagi** [comment]
@Nazar-Pa use this NGROK URL in your fulfillment
https://acdaa9ac76c9.ngrok.io/webhook

Its on my machine and working fine. I will keep it active for 30min

**Comment by abhi007tyagi** [comment]
@Nazar-Pa use Intent named as "Android Intent" and another with event as "Capture Android Event" as these are mapped to my service. Or let me know your intent names.

**Comment by Nazar-Pa** [comment]
1.Here are my Intents:

![image](https://user-images.githubusercontent.com/55276028/87748888-76ab2a80-c7f7-11ea-982f-e6af9e1450bc.png)
![image](https://user-images.githubusercontent.com/55276028/87748918-8591dd00-c7f7-11ea-879b-5c81c1d70f3f.png)
I trained by Android Intent in a way as you see above, so when I type "capture android event", the "Android Intent" intent must be detected.

2.And I tried your URL but still same error: 

![image](https://user-images.githubusercontent.com/55276028/87749089-f46f3600-c7f7-11ea-9d54-ad1c996b261b.png)

3. Here I share my Ngrok url: https://30107d7eda6c.ngrok.io/webhook

4. Yes I restart the service everytime the code changes

**Comment by abhi007tyagi** [comment]
@Nazar-Pa I am testing. For events, you don't need any training phrase, as it will interfere with event.

**Comment by abhi007tyagi** [comment]
@Nazar-Pa I am not seeing any error at my end! Try to create your project from scratch and try again. I will look into it tomorrow. I will try and share a new update over the weekend.

**Comment by Nazar-Pa** [comment]
1. So you mean it worked for you?
2. I didn't get this sentence "For events, you don't need any training phrase, as it will interfere with event". How the agent understand "test android button action" phrase then? (in your screenshot below)

![image](https://user-images.githubusercontent.com/55276028/87750122-e2db5d80-c7fa-11ea-9fd7-69737e84248f.png)

3. Ok if it works fine for you, I think there is problem in android project side with me. I will download and build it again.

**Comment by abhi007tyagi** [comment]
@Nazar-Pa test android button action is used in Android Intent not in Capture Android Event. Do not add any training phrase to Intents that have event added to it.

**Comment by Nazar-Pa** [comment]
I also used those phrases in "Android Intent" intent (as I showed above). I downloaded and built the project again but the error is still there.(

**Comment by Nazar-Pa** [comment]
hey bro, I could find the issue. It was because I already had 2 output contexts I added to my Welcome Intent. Thank you very much again.

**Comment by abhi007tyagi** [comment]
Great!
