### ISSUE TITLE
setChatUserAvatar not working 

### ISSUE THREAD

**Issue by ghost** [abhi007tyagi/Android_Dialogflow_Chatbot_Library#4]
Hi, 

Since i found out that chatUserAvatar doesn't change even if i use .setChatUserAvatar(), 
I looked up your codes and found this line. 

Drawable chatUserAvatar = ChatbotSettings.getInstance().getChatBotAvatar();

Think this line should be corrected in the right way. 
thx for your code btw :)

**Comment by abhi007tyagi** [comment]
@funny0601 Thanks for reporting :)

**Comment by abhi007tyagi** [comment]
@funny0601 resolved
