### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by kiranrayala** [abhi007tyagi/Android_Dialogflow_Chatbot_Library#5]
Hai sir I'm using your bot library I need in bot reply it's should able to ask input value using edittext can you please help me on this sir

**Comment by abhi007tyagi** [comment]
@kiranrayala Please elaborate. It is not clear what exactly you are looking for.

**Comment by kiranrayala** [comment]
Hai abhinavtyagi,


     Thanks for you reply.  I trained agent to ask few basic details  .  I am using that library but it doesn't
support  the edittext options like enter your name, enter your age based on
the end user input. Please can you help me regarding that

**Comment by abhi007tyagi** [comment]
@kiranrayala just create your intent, from node invoke text template, and enter the response. collect the response from event intent in your node.

**Comment by abhi007tyagi** [comment]
@kiranrayala you can even capture it simply without any event or webhook. Just create slots for name and age and train your intent properly to trigger question and capture response.

**Comment by kiranrayala** [comment]
Abhinavtyagi sorry how to edittext in the place of buttons

**Comment by abhi007tyagi** [comment]
@kiranrayala Edittext is already there. If you are new to Android and Dialogflow, I would recommend understanding how the widgets work in Android. You don't need webhook or any templates like buttons or cards to get a response for collecting names and age or any others information from the user. Use the edit text provided in the library to communicate for any text responses.

**Comment by kiranrayala** [comment]
> @kiranrayala Edittext is already there. If you are new to Android and Dialogflow, I would recommend understanding how the widgets work in Android. You don't need webhook or any templates like buttons or cards to get a response for collecting names and age or any others information from the user. Use the edit text provided in the library to communicate for any text responses.

Thank you @abhi007tyagi  I'm new to dailogflow now I got your point
